Updated git hooks

diff --git a/.github/hooks/pre-push b/.github/hooks/pre-push
--- a/.github/hooks/pre-push
+++ b/.github/hooks/pre-push
@@ -1,12 +1,3 @@
-#!/bin/bash
-yarn lint
-lintStatus=$?
-
-if [ $lintStatus -eq 0 ]
-then
-  echo "linting succeeded"
-  exit 0
-else
-  echo "linting failed"
-  exit 1
-fi
+#!/bin/sh
+command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
+git lfs pre-push "$@"
